import path from 'node:path';
import { readJson, writeAtomic } from './utils.mjs';

function toCssValue(token) {
  const value = token?.$value;
  if (value && typeof value === 'object' && value.colorSpace === 'srgb') {
    const [red, green, blue] = value.components.map((component) =>
      Math.round(Math.max(0, Math.min(1, component)) * 255)
    );
    if (value.alpha !== undefined && value.alpha !== 1) {
      return `rgb(${red} ${green} ${blue} / ${value.alpha})`;
    }
    return `#${[red, green, blue].map((part) => part.toString(16).padStart(2, '0')).join('')}`;
  }
  if (value && typeof value === 'object' && 'value' in value && 'unit' in value) {
    return `${value.value}${value.unit}`;
  }
  if (typeof value === 'number' || typeof value === 'string') return String(value);
  throw new Error('Unsupported DTCG token value');
}

function flatten(node, prefix = [], inheritedType = null, output = []) {
  const type = node?.$type ?? inheritedType;
  for (const [key, value] of Object.entries(node ?? {})) {
    if (key.startsWith('$')) continue;
    const pathParts = [...prefix, key];
    if (value && typeof value === 'object' && '$value' in value) {
      output.push({ name: pathParts.join('-'), path: pathParts, type: value.$type ?? type, value: toCssValue(value) });
    } else if (value && typeof value === 'object') {
      flatten(value, pathParts, value.$type ?? type, output);
    }
  }
  return output;
}

export function compileTokens(tokens) {
  const entries = flatten(tokens);
  const shared = entries.filter((entry) => entry.path[0] !== 'color' || !['light', 'dark'].includes(entry.path[1]));
  const light = entries.filter((entry) => entry.path[0] === 'color' && entry.path[1] === 'light');
  const dark = entries.filter((entry) => entry.path[0] === 'color' && entry.path[1] === 'dark');

  const variable = (entry, dropTheme = false) => {
    const parts = dropTheme ? [entry.path[0], ...entry.path.slice(2)] : entry.path;
    return `  --wpd-${parts.join('-')}: ${entry.value};`;
  };
  const css = [
    '/* Generated from DTCG tokens. Do not edit this file directly. */',
    ':root {',
    ...shared.map((entry) => variable(entry)),
    ...light.map((entry) => variable(entry, true)),
    '}',
    '',
    '.dark, [data-theme="dark"] {',
    ...dark.map((entry) => variable(entry, true)),
    '}',
    '',
    '@media (prefers-reduced-motion: reduce) {',
    '  *, *::before, *::after {',
    '    animation-duration: 0.01ms !important;',
    '    animation-iteration-count: 1 !important;',
    '    scroll-behavior: auto !important;',
    '    transition-duration: 0.01ms !important;',
    '  }',
    '}',
    ''
  ].join('\n');

  const tailwind = `/** Generated from design-system/tokens/tokens.json. */
export default {
  theme: {
    extend: {
      colors: {
        brand: 'var(--wpd-color-brand)',
        canvas: 'var(--wpd-color-canvas)',
        surface: 'var(--wpd-color-surface)',
        foreground: 'var(--wpd-color-text)',
        muted: 'var(--wpd-color-muted)',
        border: 'var(--wpd-color-border)',
        success: 'var(--wpd-color-status-success)',
        warning: 'var(--wpd-color-status-warning)',
        danger: 'var(--wpd-color-status-danger)'
      },
      borderRadius: {
        control: 'var(--wpd-radius-control)',
        container: 'var(--wpd-radius-container)',
        focal: 'var(--wpd-radius-focal)'
      },
      transitionDuration: {
        micro: 'var(--wpd-duration-micro)',
        structural: 'var(--wpd-duration-structural)'
      }
    }
  }
};
`;

  const shadcn = `/* Generated shadcn semantic mapping. */
:root {
  --background: var(--wpd-color-canvas);
  --foreground: var(--wpd-color-text);
  --card: var(--wpd-color-surface);
  --card-foreground: var(--wpd-color-text);
  --primary: var(--wpd-color-brand);
  --primary-foreground: var(--wpd-color-brand-foreground);
  --muted: var(--wpd-color-surface);
  --muted-foreground: var(--wpd-color-muted);
  --border: var(--wpd-color-border);
  --destructive: var(--wpd-color-status-danger);
  --radius: var(--wpd-radius-control);
}
`;

  return { css, tailwind, shadcn, entries };
}

export async function compileTokenFile(projectRoot) {
  const tokenFile = path.join(projectRoot, 'design-system', 'tokens', 'tokens.json');
  const tokens = await readJson(tokenFile);
  const compiled = compileTokens(tokens);
  await writeAtomic(path.join(projectRoot, 'design-system', 'tokens', 'tokens.css'), compiled.css);
  await writeAtomic(path.join(projectRoot, 'design-system', 'tokens', 'tailwind.preset.mjs'), compiled.tailwind);
  await writeAtomic(path.join(projectRoot, 'design-system', 'tokens', 'shadcn.css'), compiled.shadcn);
  return compiled;
}
